name: Auto Scrape Tieu Lam TV

on:
  repository_dispatch:
    types: [cron-trigger]
  workflow_dispatch:
jobs:
  scrape_and_update:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Thiết lập môi trường Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 1. 💡 CÀI ĐẶT MÀN HÌNH ẢO XVFB
    - name: Cài đặt Xvfb (Màn hình ảo)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    # 2. 💡 BẬT VPN WARP ĐỂ ĐỔI IP GITHUB -> IP CLOUDFLARE
    - name: Bật VPN Cloudflare WARP
      uses: fscarmen/warp-on-actions@v1.1

    - name: Cài đặt thư viện Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cài đặt trình duyệt Playwright
      run: |
        playwright install chromium
        playwright install-deps

    # 3. 💡 CHẠY PYTHON QUA MÀN HÌNH ẢO
    - name: Kích hoạt con bot đi săn m3u8
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.repository }}
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python tieulam.py

    - name: Tải ảnh chụp màn hình lên GitHub Actions
      uses: actions/upload-artifact@v4
      if: always() # Ép GitHub luôn chạy bước này kể cả khi bot văng lỗi
      with:
        name: anh-hien-truong
        path: man_hinh_bot.png
